# Generated by Django 4.2.1 on 2023-05-10 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='%Y/%m/')),
                ('boardtype', models.CharField(choices=[('BOARDTOSLEEP', '잘 자는 방법 게시판'), ('BOARDTOAWAKE', '안 자는 방법 게시판'), ('BOARDTOHEAL', '수면장애 치료 공유방')], error_messages={'message': '게시판 종류는 필수 선택 사항입니다.'}, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
