# Generated by Django 4.2.1 on 2023-05-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='%Y/%m/')),
                ('boardtype', models.CharField(choices=[('BOARDTOSLEEP', '잘 자는 방법 게시판'), ('BOARDTOAWAKE', '안 자는 방법 게시판'), ('BOARDTOHEAL', '수면장애 치료 공유방')], error_messages={'message': '선택을 꼭 하셔야 대영'}, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
